# Generated by Django 4.2.10 on 2026-03-23 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_blog_user_is_delete_user_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.blog', verbose_name='个人站点'),
        ),
    ]
