# Generated by Django 4.2.10 on 2026-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_article_upanddown_tag_comment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.FileField(blank=True, null=True, upload_to='static/css/', verbose_name='站点样式'),
        ),
    ]
