# Generated by Django 4.2.10 on 2026-03-26 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_blog_site_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.FileField(blank=True, null=True, upload_to='css/', verbose_name='站点样式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app01.blog', verbose_name='个人站点'),
        ),
    ]
