# Generated by Django 4.2.10 on 2026-05-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_alter_blog_site_theme_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "文章", "verbose_name_plural": "文章"},
        ),
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "个人站点", "verbose_name_plural": "个人站点"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "分类", "verbose_name_plural": "分类"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"verbose_name": "评论", "verbose_name_plural": "评论"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "标签", "verbose_name_plural": "标签"},
        ),
        migrations.AlterModelOptions(
            name="upanddown",
            options={"verbose_name": "点赞点踩", "verbose_name_plural": "点赞点踩"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.AlterField(
            model_name="article",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="app01.blog",
                verbose_name="个人站点",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorys",
                to="app01.blog",
                verbose_name="个人站点",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="app01.article",
                verbose_name="文章",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="app01.blog",
                verbose_name="个人站点",
            ),
        ),
    ]
