# Generated by Django 4.2.10 on 2026-06-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0008_comment_up_num_commentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
