# Generated by Django 4.2.10 on 2026-06-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0009_add_article_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("published", "已发布")],
                default="published",
                max_length=16,
                verbose_name="发布状态",
            ),
        ),
    ]
