# Generated by Django 4.2.10 on 2026-06-07 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0011_add_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="标题")),
                ("content", models.TextField(verbose_name="正文")),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="announcement/",
                        verbose_name="配图",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告",
                "ordering": ["-priority", "-create_time"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关闭时间"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.announcement",
                        verbose_name="公告",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "公告关闭记录",
                "verbose_name_plural": "公告关闭记录",
                "unique_together": {("user", "announcement")},
            },
        ),
    ]
