# Generated by Django 4.2.10 on 2026-06-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0012_add_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=128, verbose_name="文章标题"),
        ),
        migrations.AlterUniqueTogether(
            name="upanddown",
            unique_together={("user", "article")},
        ),
    ]
