# Generated by Django 4.2.10 on 2026-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0014_add_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("commented", "评论了"),
                    ("replied", "回复了"),
                    ("liked", "赞了"),
                    ("followed", "关注了你"),
                    ("published", "发布了新文章"),
                ],
                max_length=16,
                verbose_name="动作",
            ),
        ),
    ]
