# Generated by Django 4.2.10 on 2026-06-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0015_add_follow_notification_verbs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.article",
                verbose_name="相关文章",
            ),
        ),
    ]
