# Generated by Django 4.2.10 on 2026-06-08 12:19

from django.db import migrations


def create_blogs_for_users_without_one(apps, schema_editor):
    User = apps.get_model('app01', 'User')
    Blog = apps.get_model('app01', 'Blog')
    for user in User.objects.filter(blog__isnull=True):
        blog = Blog.objects.create(
            site_name=user.username,
            site_title=f'{user.username}的个人站点',
        )
        user.blog = blog
        user.save(update_fields=['blog'])


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0017_report"),
    ]

    operations = [
        migrations.RunPython(create_blogs_for_users_without_one, migrations.RunPython.noop),
    ]
